[2025-03-17 08:54:22,673] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 08:55:59,522] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 08:56:26,454] INFO in logger: [GET_INVENTORY_VALUE] User 1: Inventory value fetched | Affected: Inventory Value by Category
[2025-03-17 09:37:18,589] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-03-17 09:37:18,608] ERROR in app: Exception on /wine/top_wines [GET]
Traceback (most recent call last):
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-03-17 09:37:18,614] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-03-17 09:38:14,116] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 13:41:09,229] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 14:04:14,714] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 14:05:55,495] INFO in logger: [LOGOUT] User 1: User logged out | Affected: admin
[2025-03-17 14:38:51,571] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 14:40:02,945] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 14:40:36,799] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 14:40:50,379] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 14:42:54,138] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 14:43:17,798] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 14:43:36,397] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 14:44:49,021] ERROR in logger: [EXCEPTION] User None: Unhandled exception: ImportError
[2025-03-17 14:44:49,025] ERROR in app: Exception on /logs/logs [GET]
Traceback (most recent call last):
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 762, in handle_user_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/decorators.py", line 25, in decorated
    if is_token_blacklisted(token):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/decorators.py", line 10, in is_token_blacklisted
    from app.models import BlacklistedToken
ImportError: cannot import name 'BlacklistedToken' from 'app.models' (/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/models/__init__.py)
[2025-03-17 14:44:49,030] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-03-17 14:45:42,150] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 14:46:15,967] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 14:46:34,251] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InvalidRequestError
[2025-03-17 14:46:34,253] ERROR in app: Exception on /logs/logs [GET]
Traceback (most recent call last):
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/sql/base.py", line 2178, in _entity_namespace_key
    return getattr(ns, key)  # type: ignore
           ^^^^^^^^^^^^^^^^
AttributeError: type object 'BlacklistedToken' has no attribute 'token'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 762, in handle_user_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/decorators.py", line 25, in decorated
    if is_token_blacklisted(token):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/decorators.py", line 12, in is_token_blacklisted
    blacklisted = BlacklistedToken.query.filter_by(token=token).first()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1986, in filter_by
    clauses = [
              ^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1987, in <listcomp>
    _entity_namespace_key(from_entity, key) == value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/sql/base.py", line 2180, in _entity_namespace_key
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Entity namespace for "blacklisted_tokens" has no property "token"
[2025-03-17 14:46:34,257] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-03-17 15:06:17,119] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 15:06:27,364] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 15:07:03,515] ERROR in logger: [EXCEPTION] User None: Unhandled exception: OperationalError
[2025-03-17 15:07:03,520] ERROR in app: Exception on /logs/logs [GET]
Traceback (most recent call last):
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: blacklisted_tokens.token

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 762, in handle_user_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/decorators.py", line 25, in decorated
    if is_token_blacklisted(token):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/decorators.py", line 12, in is_token_blacklisted
    blacklisted = BlacklistedToken.query.filter_by(token=token).first()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2754, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2853, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: blacklisted_tokens.token
[SQL: SELECT blacklisted_tokens.id AS blacklisted_tokens_id, blacklisted_tokens.token AS blacklisted_tokens_token, blacklisted_tokens.created_at AS blacklisted_tokens_created_at 
FROM blacklisted_tokens 
WHERE blacklisted_tokens.token = ?
 LIMIT ? OFFSET ?]
[parameters: ('Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MjIyMDM4NywianRpIjoiYWMzNDMwNzctMTUwYS00NjUxLTk1MzQtYTEyYmU2OGYzNzEyIiwid ... (80 characters truncated) ... jk3LTQ3MTAtYjQ3MC0yODZlNGM4YjkzZjAiLCJleHAiOjE3NDIyNzQzODcsInJvbGVzIjpbImFkbWluIl0sImlzX2FkbWluIjp0cnVlfQ.Lst8fRqMKDSatp-feFE86b_iJT7pARikJCfCbmS0OWk', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-03-17 15:07:03,525] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-03-17 15:08:24,151] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 15:08:28,993] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 15:09:01,250] INFO in logger: [LOGOUT] User 1: User logged out | Affected: admin
[2025-03-17 15:15:29,271] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 15:15:44,566] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 15:15:59,549] ERROR in logger: [EXCEPTION] User None: Unhandled exception: AttributeError
[2025-03-17 15:15:59,559] ERROR in app: Exception on /logs/logs [GET]
Traceback (most recent call last):
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 762, in handle_user_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/decorators.py", line 46, in decorated
    if is_token_blacklisted(token):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/decorators.py", line 25, in is_token_blacklisted
    jti = extract_jti(token)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/decorators.py", line 12, in extract_jti
    decoded_token = jwt.decode(token, DevelopmentConfig.SECRET_KEY, algorithms=["HS256"])
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DevelopmentConfig' has no attribute 'SECRET_KEY'
[2025-03-17 15:15:59,563] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-03-17 15:19:00,657] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 15:19:08,385] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 15:19:40,084] INFO in logger: [LOGOUT] User 1: User logged out | Affected: admin
[2025-03-17 15:19:40,124] ERROR in logger: [EXCEPTION] User 1: Unhandled exception: IntegrityError
[2025-03-17 15:19:40,125] ERROR in logger: Failed to save log entry to database: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: blacklisted_tokens.jti
[SQL: INSERT INTO blacklisted_tokens (jti, created_at) VALUES (?, ?)]
[parameters: ('eead7c66-2e49-4352-96eb-380f6d2633eb', '2025-03-17 14:19:40.089492')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
[2025-03-17 15:19:40,137] ERROR in app: Exception on /auth/logout [POST]
Traceback (most recent call last):
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: blacklisted_tokens.jti

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 762, in handle_user_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/majesty-backend/app/routes/auth.py", line 159, in logout
    db.session.commit()
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/macbookpro/Documents/projects/WSS/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: blacklisted_tokens.jti
[SQL: INSERT INTO blacklisted_tokens (jti, created_at) VALUES (?, ?)]
[parameters: ('eead7c66-2e49-4352-96eb-380f6d2633eb', '2025-03-17 14:19:40.089492')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2025-03-17 15:19:40,144] ERROR in logger: [EXCEPTION] User 1: Unhandled exception: InternalServerError
[2025-03-17 15:19:49,956] INFO in logger: [LOGOUT] User 1: User logged out | Affected: admin
[2025-03-17 15:30:17,991] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 15:30:21,033] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 15:30:41,057] INFO in logger: [GET_REVENUE] User 1: Revenue calculated: 0 | Affected: Revenue
[2025-03-17 15:30:49,853] INFO in logger: [LOGOUT] User 1: User logged out | Affected: admin
[2025-03-17 15:32:40,224] INFO in logger: Wine Inventory API Started - Environment: development
[2025-03-17 15:32:45,262] INFO in logger: [LOGIN_SUCCESS] User 1: User logged in successfully | Affected: admin
[2025-03-17 15:32:56,646] INFO in logger: [GET_REVENUE] User 1: Revenue calculated: 0 | Affected: Revenue
[2025-03-17 15:33:03,066] INFO in logger: [LOGOUT] User 1: User logged out | Affected: admin
