[2025-05-05 10:21:45,627] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 10:22:11,476] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 10:22:11,591] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 10:22:11,601] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 10:22:20,686] INFO in logger: [LOGIN_FAILURE] User None: Invalid login attempt | Affected: admin
[2025-05-05 10:22:30,028] INFO in logger: [LOGIN_SUCCESS] User 2: User logged in successfully | Affected: newadmin
[2025-05-05 10:22:30,435] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 10:22:30,445] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 10:22:30,477] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 10:22:30,490] INFO in logger: [GET_REVENUE] User 2: Revenue calculated for the past 30 days: 69.98 | Affected: Revenue
[2025-05-05 10:22:30,490] INFO in logger: [GET_STOCK_BY_CATEGORY] User 2: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-05 10:22:30,493] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:22:30,526] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:22:30,538] INFO in logger: [COMPARE_SALES] User 2: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 10:22:30,541] INFO in logger: [GET_INVENTORY_VALUE] User 2: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 10:22:30,563] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 10:25:02,524] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:25:02,618] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:25:02,619] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:26:39,212] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:26:39,330] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:26:39,332] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:27:22,289] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:27:22,454] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:27:22,455] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:27:35,811] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:27:35,935] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:27:35,970] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:27:53,693] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:27:53,855] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:27:53,858] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:33:28,432] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:33:28,534] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:33:28,542] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:33:42,331] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:33:42,437] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:33:42,441] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:34:36,924] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:34:37,091] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:34:37,106] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:35:44,942] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:35:45,060] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:35:45,061] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:37:28,612] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:37:28,811] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:37:28,812] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:37:45,678] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:37:45,789] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:37:45,807] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 373 | Affected: Total Stock
[2025-05-05 10:38:44,156] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 10:39:54,034] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:40:11,616] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:51:25,332] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:51:25,336] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 0 | Affected: Total Stock
[2025-05-05 10:51:32,994] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:51:33,113] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:51:33,120] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 0 | Affected: Total Stock
[2025-05-05 10:51:50,666] INFO in logger: [LOGIN_SUCCESS] User 2: User logged in successfully | Affected: newadmin
[2025-05-05 10:51:51,069] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 10:51:51,089] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 10:51:51,098] INFO in logger: [GET_REVENUE] User 2: Revenue calculated for the past 30 days: 69.98 | Affected: Revenue
[2025-05-05 10:51:51,104] INFO in logger: [GET_STOCK_BY_CATEGORY] User 2: No stock data found | Affected: Stock by Category
[2025-05-05 10:51:51,109] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 10:51:51,122] INFO in logger: [COMPARE_SALES] User 2: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 10:51:51,154] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 10:51:51,191] INFO in logger: [GET_INVENTORY_VALUE] User 2: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 10:52:13,108] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:52:13,217] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:52:13,219] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 0 | Affected: Total Stock
[2025-05-05 10:52:16,139] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:52:16,245] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:52:16,252] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 0 | Affected: Total Stock
[2025-05-05 10:52:19,158] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 10:52:19,170] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 10:52:19,188] INFO in logger: [GET_STOCK_BY_CATEGORY] User 2: No stock data found | Affected: Stock by Category
[2025-05-05 10:52:19,191] INFO in logger: [GET_REVENUE] User 2: Revenue calculated for the past 30 days: 69.98 | Affected: Revenue
[2025-05-05 10:52:19,201] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 10:52:19,202] INFO in logger: [GET_INVENTORY_VALUE] User 2: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 10:52:19,234] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 10:52:19,271] INFO in logger: [COMPARE_SALES] User 2: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 10:53:10,490] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:53:10,664] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:53:10,665] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 0 | Affected: Total Stock
[2025-05-05 10:53:46,120] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 10:54:00,103] INFO in logger: [LOGIN_FAILURE] User None: Invalid login attempt | Affected: user
[2025-05-05 10:54:41,568] INFO in logger: [LOGIN_SUCCESS] User 2: User logged in successfully | Affected: newadmin
[2025-05-05 10:54:43,519] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 10:54:43,526] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 10:54:43,534] INFO in logger: [GET_REVENUE] User 2: Revenue calculated for the past 30 days: 69.98 | Affected: Revenue
[2025-05-05 10:54:43,541] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 10:54:43,561] INFO in logger: [GET_STOCK_BY_CATEGORY] User 2: No stock data found | Affected: Stock by Category
[2025-05-05 10:54:43,571] INFO in logger: [GET_INVENTORY_VALUE] User 2: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 10:54:43,580] INFO in logger: [COMPARE_SALES] User 2: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 10:54:59,957] INFO in logger: [UPDATE_USER_SUCCESS] User 2: User updated: 3 | Affected: sales
[2025-05-05 10:54:59,978] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 10:55:14,899] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-05 10:55:15,059] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 10:55:15,074] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 10:55:15,090] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 10:55:21,125] ERROR in logger: [SALES_LOGS_ERROR] User 3: Failed to retrieve user sales: 'InvoiceItem' object has no attribute 'wine_id'
[2025-05-05 10:55:21,168] ERROR in logger: [SALES_LOGS_ERROR] User 3: Failed to retrieve user sales: 'InvoiceItem' object has no attribute 'wine_id'
[2025-05-05 10:57:52,007] INFO in logger: [LOGIN_FAILURE] User None: Invalid login attempt | Affected: newadmin
[2025-05-05 10:57:57,485] INFO in logger: [LOGIN_SUCCESS] User 2: User logged in successfully | Affected: newadmin
[2025-05-05 10:57:57,689] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 10:57:57,706] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 10:57:57,708] INFO in logger: [GET_REVENUE] User 2: Revenue calculated for the past 30 days: 69.98 | Affected: Revenue
[2025-05-05 10:57:57,709] INFO in logger: [GET_STOCK_BY_CATEGORY] User 2: No stock data found | Affected: Stock by Category
[2025-05-05 10:57:57,729] INFO in logger: [GET_INVENTORY_VALUE] User 2: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 10:57:57,735] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 10:57:57,746] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 10:57:57,766] INFO in logger: [COMPARE_SALES] User 2: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 10:58:21,356] INFO in logger: [ADD_PRODUCT] User 2: Product added: New Product | Affected: New Product
[2025-05-05 10:58:21,379] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:58:33,105] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 10:58:33,178] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 20 | Affected: Total Stock
[2025-05-05 10:58:33,179] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:58:59,631] INFO in logger: [ADD_PRODUCT] User 2: Product added: Eba | Affected: Eba
[2025-05-05 10:58:59,654] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 10:59:17,482] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-05 10:59:17,900] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 10:59:17,918] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 69.98 | Affected: Revenue
[2025-05-05 10:59:17,922] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 10:59:17,937] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-05 10:59:17,963] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 10:59:17,968] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 10:59:17,968] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 10:59:17,989] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 10:59:23,643] ERROR in logger: [SALES_LOGS_ERROR] User 3: Failed to retrieve user sales: 'InvoiceItem' object has no attribute 'wine_id'
[2025-05-05 10:59:23,669] ERROR in logger: [SALES_LOGS_ERROR] User 3: Failed to retrieve user sales: 'InvoiceItem' object has no attribute 'wine_id'
[2025-05-05 11:03:53,115] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:17:23,589] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:19:12,009] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:22:27,526] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:22:46,623] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 220 | Affected: Total Stock
[2025-05-05 11:22:46,626] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:22:56,216] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 3 | Affected: Invoice ID 3
[2025-05-05 11:24:08,577] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:24:10,564] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:24:10,571] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 217 | Affected: Total Stock
[2025-05-05 11:24:41,879] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 4 | Affected: Invoice ID 4
[2025-05-05 11:25:20,179] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:25:23,476] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:25:23,476] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 215 | Affected: Total Stock
[2025-05-05 11:31:30,536] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:31:33,691] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 215 | Affected: Total Stock
[2025-05-05 11:31:33,692] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:31:47,073] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 5 | Affected: Invoice ID 5
[2025-05-05 11:32:16,789] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:32:34,619] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:33:08,989] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:33:09,006] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 211 | Affected: Total Stock
[2025-05-05 11:33:15,521] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 6 | Affected: Invoice ID 6
[2025-05-05 11:35:08,148] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:35:58,619] ERROR in logger: [SALES_LOGS_ERROR] User 3: Failed to retrieve user sales: 'InvoiceItem' object has no attribute 'wine_id'
[2025-05-05 11:35:58,664] ERROR in logger: [SALES_LOGS_ERROR] User 3: Failed to retrieve user sales: 'InvoiceItem' object has no attribute 'wine_id'
[2025-05-05 11:36:01,162] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 210 | Affected: Total Stock
[2025-05-05 11:36:01,162] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:39:16,148] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:39:16,339] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 210 | Affected: Total Stock
[2025-05-05 11:39:16,344] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:40:02,156] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:40:02,267] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:40:02,279] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 210 | Affected: Total Stock
[2025-05-05 11:41:05,086] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:41:05,174] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 210 | Affected: Total Stock
[2025-05-05 11:41:05,175] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:41:15,014] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 7 | Affected: Invoice ID 7
[2025-05-05 11:42:01,075] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:42:03,540] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:42:03,546] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 209 | Affected: Total Stock
[2025-05-05 11:42:09,105] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 8 | Affected: Invoice ID 8
[2025-05-05 11:42:41,640] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:42:52,831] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:43:18,151] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:43:33,477] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:43:53,997] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:44:28,211] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:44:37,985] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:44:44,927] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:44:50,379] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 208 | Affected: Total Stock
[2025-05-05 11:44:50,381] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:44:57,973] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 9 | Affected: Invoice ID 9
[2025-05-05 11:45:51,400] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:45:53,564] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:45:53,580] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 207 | Affected: Total Stock
[2025-05-05 11:46:02,150] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 10 | Affected: Invoice ID 10
[2025-05-05 11:46:20,614] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:46:24,356] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:46:39,361] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:46:58,959] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:47:00,895] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 205 | Affected: Total Stock
[2025-05-05 11:47:00,896] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:47:33,394] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 11 | Affected: Invoice ID 11
[2025-05-05 11:48:12,937] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:48:37,917] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:48:43,264] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 11:48:45,198] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 11:48:45,205] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 203 | Affected: Total Stock
[2025-05-05 11:48:55,807] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 12 | Affected: Invoice ID 12
[2025-05-05 13:53:20,454] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 13:53:47,686] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 13:53:47,864] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 4269.98 | Affected: Revenue
[2025-05-05 13:53:47,867] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 200 | Affected: Total Stock
[2025-05-05 13:53:47,867] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-05 13:53:47,913] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 13:53:47,926] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 13:53:47,952] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 13:53:47,964] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 13:53:47,973] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 13:53:48,027] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 13:53:48,083] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 13:54:09,438] INFO in logger: [LOGIN_SUCCESS] User 2: User logged in successfully | Affected: newadmin
[2025-05-05 13:54:09,625] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 13:54:09,629] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 13:54:09,642] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 13:54:09,730] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 13:54:28,581] INFO in logger: [DELETE_USER_SELF] User 2: Attempted to delete own account | Affected: newadmin
[2025-05-05 13:54:28,606] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 13:54:36,008] INFO in logger: [DELETE_USER_SUCCESS] User 2: Deleted user admin (ID: 1) | Affected: admin
[2025-05-05 13:54:36,025] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 13:54:47,217] INFO in logger: [UPDATE_USER_SUCCESS] User 2: User updated: 2 | Affected: admin
[2025-05-05 13:54:47,239] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 13:55:12,962] INFO in logger: [CREATE_USER_SUCCESS] User 2: Created user: manager | Affected: manager
[2025-05-05 13:55:12,981] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 13:55:31,998] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 13:55:32,008] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 200 | Affected: Total Stock
[2025-05-05 13:56:50,205] INFO in logger: [LOGIN_SUCCESS] User 4: User logged in successfully | Affected: manager
[2025-05-05 13:56:50,430] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 13:56:50,439] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 13:56:50,451] INFO in logger: [GET_STOCK_BY_CATEGORY] User 4: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-05 13:56:50,452] INFO in logger: [GET_REVENUE] User 4: Revenue calculated for the past 30 days: 4269.98 | Affected: Revenue
[2025-05-05 13:56:50,465] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 13:56:50,484] INFO in logger: [GET_USERS_UNAUTHORIZED] User 4: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 13:56:50,493] INFO in logger: [GET_INVENTORY_VALUE] User 4: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 13:56:50,501] INFO in logger: [COMPARE_SALES] User 4: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 13:57:08,380] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-05 13:57:08,501] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 13:57:08,531] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 13:57:08,537] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 13:57:08,548] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 13:57:21,916] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 13 | Affected: Invoice ID 13
[2025-05-05 13:57:37,418] ERROR in logger: [SALES_LOGS_ERROR] User 3: Failed to retrieve user sales: 'InvoiceItem' object has no attribute 'wine_id'
[2025-05-05 13:57:37,463] ERROR in logger: [SALES_LOGS_ERROR] User 3: Failed to retrieve user sales: 'InvoiceItem' object has no attribute 'wine_id'
[2025-05-05 13:57:56,131] INFO in logger: [LOGIN_SUCCESS] User 2: User logged in successfully | Affected: admin
[2025-05-05 13:57:56,338] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 13:57:56,359] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 13:57:56,362] INFO in logger: [GET_REVENUE] User 2: Revenue calculated for the past 30 days: 4669.98 | Affected: Revenue
[2025-05-05 13:57:56,373] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 13:57:56,380] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 13:59:59,651] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 14:00:20,286] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 14:03:45,666] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 14:04:39,299] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 14:05:51,779] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 14:06:17,799] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 14:08:45,136] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 14:09:05,592] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-05 14:09:07,419] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 4669.98 | Affected: Revenue
[2025-05-05 14:09:07,427] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-05 14:09:07,445] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 198 | Affected: Total Stock
[2025-05-05 14:09:07,457] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 14:09:07,471] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 14:09:07,473] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 14:09:07,476] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 14:09:07,486] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 14:09:07,487] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 14:09:07,510] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 14:09:16,303] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:10:05,323] INFO in logger: [LOGIN_SUCCESS] User 4: User logged in successfully | Affected: manager
[2025-05-05 14:10:05,735] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 14:10:05,744] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 14:10:05,754] INFO in logger: [GET_REVENUE] User 4: Revenue calculated for the past 30 days: 4669.98 | Affected: Revenue
[2025-05-05 14:10:05,757] INFO in logger: [GET_TOTAL_STOCK] User 4: Total stock checked: 198 | Affected: Total Stock
[2025-05-05 14:10:05,765] INFO in logger: [GET_STOCK_BY_CATEGORY] User 4: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-05 14:10:05,769] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 14:10:05,784] INFO in logger: [GET_ALL_PRODUCTS] User 4: Fetched all products | Affected: All products
[2025-05-05 14:10:05,798] INFO in logger: [COMPARE_SALES] User 4: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 14:10:05,812] INFO in logger: [GET_USERS_UNAUTHORIZED] User 4: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 14:10:05,813] INFO in logger: [GET_INVENTORY_VALUE] User 4: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 14:10:23,272] INFO in logger: [CHECKOUT_SUCCESS] User 4: Checkout completed for invoice 14 | Affected: Invoice ID 14
[2025-05-05 14:10:36,288] INFO in logger: [LOGIN_SUCCESS] User 2: User logged in successfully | Affected: admin
[2025-05-05 14:10:36,513] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 14:10:36,518] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 14:10:36,528] INFO in logger: [GET_REVENUE] User 2: Revenue calculated for the past 30 days: 4969.98 | Affected: Revenue
[2025-05-05 14:10:36,535] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 14:10:36,573] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 14:12:21,523] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 14:14:14,421] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 14:14:24,963] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 14:14:48,872] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 14:18:02,951] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 14:18:02,976] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 14:22:58,919] INFO in logger: [LOGIN_FAILURE] User None: Invalid login attempt | Affected: user
[2025-05-05 14:23:03,497] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-05 14:23:04,032] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 14:23:04,049] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 14:23:04,059] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 4969.98 | Affected: Revenue
[2025-05-05 14:23:04,065] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 197 | Affected: Total Stock
[2025-05-05 14:23:04,075] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-05 14:23:04,086] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 14:23:04,099] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 14:23:04,115] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 14:23:04,125] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 14:23:04,129] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 14:25:02,525] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 197 | Affected: Total Stock
[2025-05-05 14:25:02,527] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 14:25:10,730] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 15 | Affected: Invoice ID 15
[2025-05-05 14:29:08,795] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:29:09,528] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:32:45,916] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 14:32:58,313] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:33:49,932] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:33:50,337] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:33:58,008] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:33:58,226] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:37:23,143] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 14:37:23,150] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 196 | Affected: Total Stock
[2025-05-05 14:52:05,686] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:52:06,523] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:54:10,211] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:54:10,995] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:57:29,988] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:57:30,894] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:58:42,344] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:58:44,221] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:59:49,322] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 14:59:50,117] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:05:46,632] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:05:47,475] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:06:00,645] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:06:02,156] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:06:10,466] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:06:10,478] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:10:56,079] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:10:59,308] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 15:10:59,413] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:11:15,080] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:11:15,162] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 15:11:17,439] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:11:32,887] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 15:11:32,948] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 18:46:43,675] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 18:46:52,217] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 18:46:52,232] INFO in logger: [GET_USER_UNAUTHORIZED] User 3: Unauthorized attempt to view user 3 | Affected: User ID 3
[2025-05-05 18:49:10,464] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 18:49:10,586] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 18:49:10,603] INFO in logger: [GET_USER_UNAUTHORIZED] User 3: Unauthorized attempt to view user 3 | Affected: User ID 3
[2025-05-05 18:49:49,566] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 18:50:04,394] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 18:50:04,485] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 18:50:04,632] INFO in logger: [GET_USER_UNAUTHORIZED] User 3: Unauthorized attempt to view user 3 | Affected: User ID 3
[2025-05-05 19:00:45,662] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 19:00:51,549] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:00:51,699] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:00:51,732] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:01:02,736] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:01:02,844] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:01:02,844] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:02:09,719] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:02:09,967] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:02:09,967] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:02:12,183] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:02:12,276] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:02:12,290] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:03:27,542] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:03:28,155] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:03:28,157] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:03:28,495] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:03:28,740] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:03:28,743] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:03:53,992] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:03:54,382] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:03:54,383] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:03:55,869] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:03:56,051] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:03:56,057] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:04:43,121] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:04:43,208] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:04:43,211] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:04:45,154] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:04:45,237] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:04:45,238] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:05:17,760] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:05:17,907] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:05:17,908] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:05:18,894] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:05:19,008] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:05:19,028] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:06:22,201] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:06:22,353] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:06:22,354] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:06:22,909] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:06:23,109] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:06:23,111] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:07:25,028] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:07:25,208] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:07:25,211] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:07:25,351] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:07:25,509] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:07:25,510] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:09:28,875] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:09:28,998] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:09:29,011] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:09:29,429] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:09:29,527] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:09:29,536] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:09:50,538] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:09:50,632] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:09:50,632] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:09:52,174] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:09:52,299] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:09:52,333] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:10:47,438] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:10:47,579] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:10:47,582] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:10:47,774] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:10:47,908] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:10:47,914] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:11:02,866] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:11:02,951] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:11:02,988] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:11:04,571] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:11:04,618] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:11:04,664] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:11:18,220] INFO in logger: [UPDATE_USER_ERROR] User 3: Unauthorized attempt to update user | Affected: sales
[2025-05-05 19:11:18,241] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:13:49,606] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 19:14:12,022] INFO in logger: [UPDATE_USER_ERROR] User 3: Unauthorized attempt to update user | Affected: sales
[2025-05-05 19:14:12,080] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:14:16,641] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:14:16,763] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:14:16,797] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:14:25,966] INFO in logger: [UPDATE_USER_ERROR] User 3: Unauthorized attempt to update user | Affected: sales
[2025-05-05 19:14:26,008] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:14:42,611] INFO in logger: [UPDATE_USER_ERROR] User 3: Unauthorized attempt to update user | Affected: sales
[2025-05-05 19:14:42,684] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:16:24,554] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 19:16:31,660] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:16:31,808] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:16:31,809] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:16:36,571] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:16:36,663] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:16:36,663] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:16:48,047] INFO in logger: [UPDATE_USER_ERROR] User 3: Unauthorized attempt to update user | Affected: sales
[2025-05-05 19:16:48,087] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:19:00,097] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 19:19:06,319] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:19:06,481] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:19:06,502] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:19:17,970] INFO in logger: [UPDATE_USER_IGNORED_FIELDS] User 3: Ignored attempt to modify restricted fields (roles/is_admin) | Affected: sales
[2025-05-05 19:19:17,979] INFO in logger: [UPDATE_USER_SUCCESS] User 3: User updated: 3 | Affected: sales
[2025-05-05 19:19:17,996] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:19:26,190] INFO in logger: [UPDATE_USER_IGNORED_FIELDS] User 3: Ignored attempt to modify restricted fields (roles/is_admin) | Affected: sales
[2025-05-05 19:19:26,195] INFO in logger: [UPDATE_USER_SUCCESS] User 3: User updated: 3 | Affected: sales
[2025-05-05 19:19:26,216] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:19:31,732] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:19:31,810] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:19:31,838] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:20:46,363] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:20:46,425] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:20:46,426] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:20:47,993] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:20:48,098] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-05 19:20:48,098] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:20:56,792] INFO in logger: [UPDATE_USER_IGNORED_FIELDS] User 3: Ignored attempt to modify restricted fields (roles/is_admin) | Affected: salesgirl
[2025-05-05 19:20:56,805] INFO in logger: [UPDATE_USER_SUCCESS] User 3: User updated: 3 | Affected: salesgirl
[2025-05-05 19:20:56,873] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:20:56,881] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:23:49,623] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:23:49,790] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:23:49,800] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:23:51,260] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:23:51,327] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:23:51,348] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:24:07,935] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:24:08,038] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:24:08,107] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:24:09,716] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:24:09,884] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:24:09,885] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:25:13,273] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:25:13,374] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:25:13,378] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:25:13,950] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:25:14,031] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:25:14,036] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:26:56,672] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:26:56,755] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:26:56,757] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:26:56,923] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:26:57,095] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:26:57,173] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:27:25,916] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:27:26,054] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:27:26,055] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:27:27,272] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:28:20,599] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:28:20,916] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:28:20,916] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:28:23,072] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:28:31,241] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:28:31,426] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:28:31,427] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:28:32,965] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:28:42,294] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:28:42,432] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:28:42,433] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:28:45,103] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:28:53,715] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:28:53,885] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:28:53,892] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:28:59,943] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:29:00,251] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:29:00,348] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:29:00,354] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:29:09,265] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:29:09,378] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:29:09,389] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:29:12,965] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:29:16,028] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:29:16,095] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-05 19:29:16,096] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: salesgirl
[2025-05-05 19:29:18,167] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:30:36,147] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:30:53,785] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:31:02,046] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:31:11,362] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:31:24,701] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:31:39,839] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:31:58,482] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-05 19:32:23,390] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 196 | Affected: Total Stock
[2025-05-05 19:32:23,391] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-05 19:32:41,510] INFO in logger: [LOGIN_SUCCESS] User 2: User logged in successfully | Affected: admin
[2025-05-05 19:32:42,314] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-05 19:32:42,326] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-05 19:32:42,335] INFO in logger: [GET_REVENUE] User 2: Revenue calculated for the past 30 days: 5269.98 | Affected: Revenue
[2025-05-05 19:32:42,339] INFO in logger: [GET_STOCK_BY_CATEGORY] User 2: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-05 19:32:42,361] INFO in logger: [GET_INVENTORY_VALUE] User 2: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-05 19:32:42,373] INFO in logger: [COMPARE_SALES] User 2: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-05 19:32:42,379] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-05 19:32:42,385] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 19:32:46,604] INFO in logger: [GET_USER_SUCCESS] User 2: User data retrieved for user 2 | Affected: admin
[2025-05-05 19:33:06,547] INFO in logger: [UPDATE_PRODUCT_SUCCESS] User 2: Updated New Product | Affected: New Product
[2025-05-05 19:33:06,577] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 19:33:32,926] INFO in logger: [UPDATE_PRODUCT_SUCCESS] User 2: Updated New Product | Affected: New Product
[2025-05-05 19:33:32,971] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-05 19:34:51,245] INFO in logger: [CHECK_TOKEN_VALID] User 2: Token is valid | Affected: Token System
[2025-05-05 19:34:51,324] INFO in logger: [GET_USER_SUCCESS] User 2: User data retrieved for user 2 | Affected: admin
[2025-05-05 19:34:51,329] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-05 19:54:43,271] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-05 19:58:19,630] INFO in logger: Wine Inventory API Started - Environment: development
