[2025-05-09 02:03:21,738] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-09 02:08:41,054] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-09 02:09:06,973] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:09:15,907] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1361 | Affected: Total Stock
[2025-05-09 02:09:15,916] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:12:44,721] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:12:49,912] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:13:02,924] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:13:43,916] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:17:16,744] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:17:42,669] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:18:01,045] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:19:28,741] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:20:05,156] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:21:16,637] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:21:28,202] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:21:41,322] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:21:49,804] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:21:57,635] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:22:03,757] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:22:09,774] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:22:16,677] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:22:24,112] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:22:37,703] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:23:09,280] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:23:31,763] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:23:36,880] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:23:44,713] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:23:48,361] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:23:48,366] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1361 | Affected: Total Stock
[2025-05-09 02:23:57,522] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:23:57,642] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:23:57,661] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1361 | Affected: Total Stock
[2025-05-09 02:24:40,585] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:25:20,825] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:25:32,710] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:25:48,497] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:26:08,103] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:26:15,539] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:26:22,304] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:26:41,833] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:26:47,545] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:26:53,209] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:27:01,688] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:27:11,506] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:28:31,488] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:30:11,850] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:30:28,447] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:30:43,377] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:31:06,923] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:31:23,359] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:32:27,067] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:32:35,713] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:32:46,280] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1361 | Affected: Total Stock
[2025-05-09 02:32:46,290] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:32:59,444] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:32:59,698] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1361 | Affected: Total Stock
[2025-05-09 02:32:59,713] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:35:27,299] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:35:27,373] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1361 | Affected: Total Stock
[2025-05-09 02:35:27,405] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:37:38,234] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:37:38,306] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1361 | Affected: Total Stock
[2025-05-09 02:37:38,317] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:40:28,681] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1361 | Affected: Total Stock
[2025-05-09 02:40:28,695] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:40:40,324] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:40:40,474] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1361 | Affected: Total Stock
[2025-05-09 02:40:40,485] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:40:50,988] INFO in logger: [CHECKOUT_SUCCESS] User 3: Checkout completed for invoice 22 | Affected: Invoice ID 22
[2025-05-09 02:41:21,135] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-09 02:41:22,667] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 02:41:22,691] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 02:41:22,697] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 02:41:22,722] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 02:41:22,787] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 02:41:22,787] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 02:41:22,814] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 02:41:22,826] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 02:41:54,720] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 02:41:54,738] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-09 02:42:19,672] INFO in logger: [LOGIN_FAILURE] User None: Invalid login attempt | Affected: manger
[2025-05-09 02:42:24,493] INFO in logger: [LOGIN_SUCCESS] User 4: User logged in successfully | Affected: manager
[2025-05-09 02:42:24,705] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 02:42:24,729] INFO in logger: [GET_USERS_UNAUTHORIZED] User 4: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 02:42:24,740] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 02:42:24,758] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 02:50:44,646] INFO in logger: [CHECK_TOKEN_VALID] User 4: Token is valid | Affected: Token System
[2025-05-09 02:50:44,979] INFO in logger: [GET_TOTAL_STOCK] User 4: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 02:50:44,995] INFO in logger: [GET_ALL_PRODUCTS] User 4: Fetched all products | Affected: All products
[2025-05-09 02:52:06,180] INFO in logger: [CHECK_TOKEN_VALID] User 4: Token is valid | Affected: Token System
[2025-05-09 02:52:06,383] INFO in logger: [GET_TOTAL_STOCK] User 4: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 02:52:06,397] INFO in logger: [GET_ALL_PRODUCTS] User 4: Fetched all products | Affected: All products
[2025-05-09 02:53:45,566] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-09 02:54:13,356] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:54:13,483] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 02:54:13,489] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 02:54:13,497] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 02:54:13,511] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 02:54:13,516] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 02:54:13,533] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 02:54:13,557] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 02:54:13,564] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 02:54:13,687] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 02:54:13,730] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:54:27,010] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-09 02:56:49,182] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:56:49,357] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 02:56:49,394] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 02:56:49,401] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 02:56:49,422] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 02:56:49,441] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 02:56:49,452] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 02:56:49,472] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 02:56:49,480] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 02:56:49,498] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 02:56:49,579] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:56:57,471] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-09 02:57:26,724] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 02:57:26,964] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 02:57:26,977] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 02:57:26,980] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 02:57:26,987] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 02:57:27,001] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 02:57:27,011] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 02:57:27,051] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 02:57:27,052] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 02:57:27,135] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 02:57:27,136] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 02:57:35,233] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-09 03:00:53,005] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 03:00:53,228] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:00:53,230] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:00:53,242] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:00:53,247] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:00:53,258] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:00:53,282] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:00:53,298] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:00:53,303] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 03:00:53,373] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:00:53,379] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:00:58,722] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 03:00:58,879] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:00:58,889] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:00:58,899] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:00:58,903] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:00:58,916] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:00:58,926] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:00:58,951] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:00:58,952] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:00:58,965] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 03:00:58,978] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:01:31,594] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 03:01:31,709] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:01:31,723] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:01:31,772] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:01:31,749] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:01:31,786] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:01:31,805] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:01:31,806] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:01:31,807] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 03:01:31,842] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:01:31,852] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:02:49,932] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 03:02:50,060] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:02:50,069] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:02:50,079] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:02:50,104] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:02:50,115] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:02:50,120] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:02:50,128] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:02:50,136] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:02:50,199] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:02:50,209] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 03:03:04,844] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-09 03:03:05,405] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:03:05,418] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:03:05,422] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:03:05,442] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:03:05,446] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:03:05,449] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:03:05,460] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:03:05,468] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:03:05,486] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:03:05,491] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 03:03:25,627] INFO in logger: [LOGIN_SUCCESS] User 4: User logged in successfully | Affected: manager
[2025-05-09 03:03:26,354] INFO in logger: [GET_REVENUE] User 4: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:03:26,364] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:03:26,368] INFO in logger: [GET_STOCK_BY_CATEGORY] User 4: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:03:26,373] INFO in logger: [GET_TOTAL_STOCK] User 4: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:03:26,376] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:03:26,385] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:03:26,456] INFO in logger: [GET_USERS_UNAUTHORIZED] User 4: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:03:26,466] INFO in logger: [COMPARE_SALES] User 4: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:03:26,467] INFO in logger: [GET_INVENTORY_VALUE] User 4: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:03:26,467] INFO in logger: [GET_ALL_PRODUCTS] User 4: Fetched all products | Affected: All products
[2025-05-09 03:03:36,068] INFO in logger: [GET_USERS_UNAUTHORIZED] User 4: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:03:36,077] INFO in logger: [GET_USER_SUCCESS] User 4: User data retrieved for user 4 | Affected: manager
[2025-05-09 03:03:51,850] INFO in logger: [LOGIN_SUCCESS] User 2: User logged in successfully | Affected: admin
[2025-05-09 03:03:52,394] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:03:52,408] INFO in logger: [GET_REVENUE] User 2: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:03:52,420] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:03:52,443] INFO in logger: [GET_TOTAL_STOCK] User 2: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:03:52,455] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:03:52,459] INFO in logger: [GET_STOCK_BY_CATEGORY] User 2: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:03:52,477] INFO in logger: [COMPARE_SALES] User 2: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:03:52,526] INFO in logger: [GET_INVENTORY_VALUE] User 2: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:03:52,527] INFO in logger: [GET_USERS_SUCCESS] User 2: Admin retrieved user list | Affected: User Management
[2025-05-09 03:03:52,528] INFO in logger: [GET_ALL_PRODUCTS] User 2: Fetched all products | Affected: All products
[2025-05-09 03:03:54,672] INFO in logger: [GET_USER_SUCCESS] User 2: User data retrieved for user 2 | Affected: admin
[2025-05-09 03:04:09,171] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-09 03:04:09,718] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:04:09,732] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:04:09,743] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:04:09,748] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:04:09,749] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:04:09,759] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:04:09,803] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:04:09,806] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:04:09,807] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:04:09,924] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 03:04:11,646] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:04:11,674] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-09 03:04:59,615] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 03:04:59,790] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:04:59,792] INFO in logger: [GET_USER_SUCCESS] User 3: User data retrieved for user 3 | Affected: sales
[2025-05-09 03:05:01,761] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:05:01,765] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:05:01,793] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:05:01,799] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:05:01,810] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:05:01,823] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:05:01,835] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:05:01,854] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:05:01,860] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:05:01,890] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 03:05:44,955] INFO in logger: [CHECK_TOKEN_VALID] User 3: Token is valid | Affected: Token System
[2025-05-09 03:05:45,247] ERROR in logger: [EXCEPTION] User None: Unhandled exception: NotFound
[2025-05-09 03:05:45,256] ERROR in app: Exception on /products/top_wines [OPTIONS]
Traceback (most recent call last):
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/app/utils/logger.py", line 194, in log_exception
    raise exception
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/macbook/EverythingProgramming/inventory_management_system/majesty-backend/backend/lib/python3.13/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-05-09 03:05:45,267] INFO in logger: [GET_REVENUE] User 3: Revenue calculated for the past 30 days: 15469.98 | Affected: Revenue
[2025-05-09 03:05:45,278] INFO in logger: [GET_STOCK_BY_CATEGORY] User 3: Stock by category fetched successfully | Affected: Stock by Category
[2025-05-09 03:05:45,278] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:05:45,288] ERROR in logger: [EXCEPTION] User None: Unhandled exception: InternalServerError
[2025-05-09 03:05:45,338] INFO in logger: [GET_USERS_UNAUTHORIZED] User 3: Unauthorized attempt to view users | Affected: User Management
[2025-05-09 03:05:45,341] INFO in logger: [COMPARE_SALES] User 3: Sales compared: Growth Factor = 2.0, Percentage Change = 100% | Affected: Sales Comparison
[2025-05-09 03:05:45,482] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 03:05:45,495] INFO in logger: [GET_INVENTORY_VALUE] User 3: Inventory value fetched | Affected: Inventory Value by Category
[2025-05-09 03:06:04,546] INFO in logger: [LOGIN_SUCCESS] User 3: User logged in successfully | Affected: sales
[2025-05-09 03:06:05,242] INFO in logger: [GET_TOTAL_STOCK] User 3: Total stock checked: 1360 | Affected: Total Stock
[2025-05-09 03:06:05,258] INFO in logger: [GET_ALL_PRODUCTS] User 3: Fetched all products | Affected: All products
[2025-05-09 10:36:58,468] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-09 10:40:00,019] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-09 10:40:45,390] INFO in logger: Wine Inventory API Started - Environment: development
[2025-05-09 10:40:59,631] INFO in logger: Wine Inventory API Started - Environment: development
